### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by addebc** [agrieco/merakicmx#1]
Traceback (most recent call last):
  File "/config/custom_components/device_tracker/merakicmx.py", line 74, in post
    data = yield from request.json()
  File "/usr/lib/python3.6/site-packages/aiohttp/web_request.py", line 469, in json
    return loads(body)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/ban.py", line 58, in ban_middleware_handler
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/__init__.py", line 424, in handle
    result = yield from result
  File "/config/custom_components/device_tracker/merakicmx.py", line 76, in post
    return self.json_message('Invalid JSON', HTTP_BAD_REQUEST)
NameError: name 'HTTP_BAD_REQUEST' is not defined

**Comment by agrieco** [comment]
Please turn on debug logging for HASS and send those over.  

Note, I also fixed a formatting error on the documentation README- step 4.

**Comment by agrieco** [comment]
Please use this going forward:

https://www.home-assistant.io/components/device_tracker.meraki/
